version: '2.4'

services:
  rabbitmq:
    build: 
      context: ./rabbitmq
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: my-rabbit
    volumes:
      - "./data/rabbit:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.7
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 5
    cpus: '4'
    mem_limit: 1024M

  redis:
    image: redis:6.0-alpine
    restart: unless-stopped
    volumes:
      - "./data/redis:/data"
    ports:
      - "6380:6379"
    command:
      - redis-server
      - --save ''
      - --notify-keyspace-events Ks
      - --maxmemory-policy volatile-ttl
      - --maxmemory 512mb
    cpus: '2'
    mem_limit: 1024M
