version: '2.4'

services:
  semantic-clustering:
    build:
      context: ../..
      dockerfile: ./producers/short-texts-clustering/Dockerfile
    image: semantic-clustering:latest
    # NOTE: network_mode here is only for test purposes - 
    #       - in real life rabbit and redis usually not running 
    #       on the same machine with your app
    network_mode: "host"
    restart: unless-stopped 
    ports:
      - "5000:5000"
    env_file:
      - "../../variables.env"
      - "variables.env"
    # NOTE: uncomment for tests
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    cpus: '8'
    mem_limit: 8192M
